name: Workflow Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Run Action Lint
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Run Action Lint
      - name: Run Action Lint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
